name: Build and Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-13
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          xcodebuild build -project GameRAW.xcodeproj \
          -scheme GameRAW \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Test
        run: |
          xcodebuild \
          -project GameRAW.xcodeproj \
          -scheme GameRAW \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' \
          clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
